

<form action="filtrarAdmin" method="GET">
    <select name="categoria_id">
        <option value="">Seleccione una categoría</option>
        <?php foreach ($categorias as $categoria): ?>
            <option value=<?= $categoria->id_categoria; ?>>
                <?= $categoria->nombre; ?>
            </option>
        <?php endforeach; ?>
    </select>
    <button type="submit" class="btn">Filtrar</button>
    <button type="reset " class= "btn">borrar filtros</button>
</form>
