<?php
require "guitarraAdmin.phtml";
?>

<div class="container mt-5">
    <h2 class="text-center mb-4">Cambiar imagen de la Guitarra</h2>
    <form action="updateImg/<?=$guitarra->id_guitarra?>" method="POST" class="p-4 border rounded shadow">
    <div class="mb-3">
            <label for="imagen_url" class="form-label">Imagen de la guitarra (URL)</label>
            <input type="url" class="form-control" id="imagen_url" name="imagen_url" placeholder="Ingrese la nueva URL de la imagen" required>
        </div>
        <button type="submit" class="btn btn-primary w-100">Cambiar</button>
    </form>
</div>

<!-- Añade Bootstrap JS si lo necesitas -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"></script>


<?php
require "footer.phtml";
?>