<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">    
</head>
<body>

    <!-- Contenedor principal -->
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <!-- Formulario de Login -->
                <div class="login-container">
                    <div class="login-header">
                        <h2>Iniciar Sesión</h2>
                    </div>

                    <!-- Formulario de login -->
                    <form action="login" method="post">
                        <div class="mb-3">
                            <label for="nickname" class="form-label">Usuario</label>
                            <input type="text" class="form-control" id="nickname" name="nickname" placeholder="usuario1234" required>
                        </div>

                        <div class="mb-3">
                            <label for="password" class="form-label">Contraseña</label>
                            <input type="password" class="form-control" id="password" name="password" placeholder="Ingresa tu contraseña" required>
                        </div>

                        <!-- Botón de enviar -->
                        <button type="submit" class="btn btn-custom btn-primary">Ingresar</button>

                        <!-- Mensaje de registro -->
                        <div class="text-center mt-3">
                            <p>¿No tienes cuenta? <a href="#">Regístrate</a></p>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</html>
  
