<?php
require "guitarra.phtml";
?>

<div class="form">
    <form action="updateCategoria/<?=$guitarra->id_guitarra?>" method="POST" class="form">
        <select name="categoria_id">
            <option value="">Seleccione una categoría</option>
            <?php foreach ($categorias as $categoria): ?>
                <option value="<?= $categoria->id_categoria; ?>">
                    <?= $categoria->nombre; ?>
                </option>
            <?php endforeach; ?>
        </select>
        <button type="submit" class="btn">Cambiar</button>
    </form>
</div>

<?php
require "footer.phtml";
?>