<?php
require "header.phtml";
?>
<section class="d-flex justify-content-center">
    <div class="col-md-4 mb-4">
        <div class="card h-100 card-guitar only">
            <!-- Aquí va la imagen de la guitarra -->
            <img src="<?= $guitarra->imagen_url; ?>" class="card-img-top" alt="Imagen de la guitarra">
            <div class="card-body">
                <h5 class="card-title text-center"><?= $guitarra->nombre; ?></h5>
                <p class="card-text">Categoría: <?= $guitarra->categoria_nombre; ?></p>
                <p class="card-text">Precio: $<?= $guitarra->precio; ?></p>
            </div>
        </div>

    </div>
</section>

<!-- Añade Bootstrap JS si lo necesitas -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"></script>