<?php
require "headerAdmin.phtml";
?>

<div class="container">
    <h1>GUITARRAS</h1>
    <aside>
        <ul class="list display-inline">
            <h3>Categorias</h3>
            <?php foreach ($categorias as $categoria): ?>
    <?php if ($categoria->nombre != "sin_categoria"): ?>
        <li><?= $categoria->nombre; ?></li>
        <button class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#deleteModal<?= $categoria->id_categoria; ?>">Eliminar</button>

        <!-- Modal -->
        <div class="modal fade" id="deleteModal<?= $categoria->id_categoria; ?>" tabindex="-1" aria-labelledby="deleteModalLabel<?= $categoria->id_categoria; ?>" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="deleteModalLabel<?= $categoria->id_categoria; ?>">Confirmación de eliminación</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        ¿Seguro que quieres eliminar la categoría: <strong><?= $categoria->nombre; ?></strong>?
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">No</button>

                        <!-- Botón para confirmar eliminación -->
                        <a href="deleteCategoria/<?= $categoria->id_categoria; ?>" class="btn btn-danger">Sí</a>
                    </div>
                </div>
            </div>
        </div>
    <?php endif; ?>
<?php endforeach; ?>
        </ul>
        <?php require "filtroAdmin.phtml"; ?>
    </aside>
    <ul class="list">
        <?php foreach ($guitarras as $guitarra): ?>
            <li>
                <h2><a href="guitarraAdmin/<?= $guitarra->id_guitarra; ?>"><?= $guitarra->nombre; ?></a></h2>
                <span>Categoria: <?= $guitarra->categoria_nombre; ?></span>
                <p>Precio: $<?= $guitarra->precio; ?></p>
                <button class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#deleteModal<?=$guitarra->id_guitarra;?>">Eliminar</button>
            </li>
            <!-- Modal -->
            <div class="modal fade" id="deleteModal<?=$guitarra->id_guitarra;?>" tabindex="-1" aria-labelledby="deleteModalLabel<?=$guitarra->id_guitarra;?>" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="deleteModalLabel<?=$guitarra->id_guitarra;?>">Confirmación de eliminación</h5>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body">
                            ¿Seguro que quieres eliminar la guitarra: <strong><?=$guitarra->nombre?></strong>?
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">No</button>


                            <a class= "btn btn-danger"href="deleteGuitarra/<?= $guitarra->id_guitarra; ?>">  Sí</a>
                        </div>
                    </div>
                </div>
            </div>
        <?php endforeach ?>
    </ul>
</div>
</main>



<?php
require "footer.phtml"
?>