<?php
require "header.phtml";
?>

<div class="container mt-5">
    <h1 class="text-center mb-5">GUITARRAS</h1>
    <div class="row">
        <div class="col-md-3">
            <aside>
                <h3>Categorías</h3>
                <ul class="list-group">
                    <?php foreach ($categorias as $categoria): ?>
                        <?php if ($categoria->nombre != "sin_categoria"): ?>
                            <li class="list-group-item">
                                <?= $categoria->nombre; ?>
                            </li>
                        <?php endif; ?>
                    <?php endforeach; ?>
                </ul>
                <?php require "filtro.phtml"; ?>
                <?php require "Orden.phtml"; ?>
            </aside>
        </div>

        <div class="col-md-9">
            <div class="row">
                <?php foreach ($guitarras as $guitarra): ?>
                   <div class="col-md-4 mb-4">
                   <a href="guitarra/<?= $guitarra->id_guitarra; ?>"><div class="card h-100 card-guitar">
                            <!-- Imagen de la guitarra (reemplazar la ruta con la imagen correcta) -->
                            <img src="<?= $guitarra->imagen_url; ?>" class="card-img-top" alt="Imagen de la guitarra">

                            <div class="card-body">
                                <h5 class="card-title text-center">
                                    <a href="guitarra/<?= $guitarra->id_guitarra; ?>" class="anchor">
                                        <?= $guitarra->nombre; ?>
                                    </a>
                                </h5>
                                <p class="card-text">Categoría: <?= $guitarra->categoria_nombre; ?></p>
                                <p class="card-text">Precio: $<?= $guitarra->precio; ?></p>
                            </div>
                        </div></a>
                    </div>
                <?php endforeach; ?>
            </div>
        </div>
    </div>
</div>




<?php
require "footer.phtml"
?>