<div class="container mt-5">
    <h2 class="text-center mb-4">Ordenar Guitarras</h2>
    <form action="ordenar" method="GET" class="p-4 border rounded shadow">
        <div class="mb-3">
            <label for="orden" class="form-label">Seleccione</label>
            <select class="form-select" id="orden" name="orden">
                <option value="">Seleccione un orden</option>
                <option value="ordenPrecio">Precio</option>
                <option value="ordenNombre">Nombre</option>
            </select>
        </div>
        <div class="d-flex justify-content-between filters">
            <button type="submit" class="btn btn-primary btn-lg">Ordenar</button>
            <button type="reset" class="btn btn-outline-secondary btn-lg">Borrar</button>
        </div>

    </form>
</div>

<!-- Añade Bootstrap JS si lo necesitas -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"></script>